The querystring package has been depricated
leerob/leerob.io pull request #432
Opened 2021-12-24 15:16 UTC by OJPARKINSON

I was working with the Spotify intergration and it's a perfect fit for my use case but I noticed that querystring has been depricated by the owner so it might want swapping out. Although, it is still downloaded 21 million times a weekly 😕

https://www.npmjs.com/package/querystring

2022-01-08 04:25 UTC, leerob requested changes
URLSearchParams looks to be the built-in replacement - could we use that?

https://nodejs.org/api/url.html#class-urlsearchparams

2022-01-08 10:11 UTC, Music47ell commented
Yes you could. I use it myself and it works.

```ts
body: new URLSearchParams({
      grant_type: 'refresh_token',
      refresh_token,
}),
```

2022-01-10 09:05 UTC, OJPARKINSON commented
I also noticed that the changes need to be made in other places as well.

2022-01-10 22:27 UTC, leerob approved these changes

2022-01-10 22:37 UTC, merged